package app.domain.model;

/**
 * Represents a Sample through:
 * a MyBarcode (containing the barcode number and the barcode generated by the API) and a collecting Date.
 *
 * @author Ana Albergaria
 */


public class Sample {
    /**
     * The myBarcode of the Sample.
     */
    private MyBarcode myBarcode;


    /**
     * Builds a Sample's instance receiving:
     * the MyBarcode
     *
     * @param myBarcode the myBarcode of the Sample
     */
    public Sample(MyBarcode myBarcode) {
        this.myBarcode = new MyBarcode(myBarcode);
    }

    /**
     * Returns the myBarcode of the Sample
     *
     * @return myBarcode of the Sample
     */
    public MyBarcode getMyBarcode() {
        return new MyBarcode(myBarcode);
    }

    /**
     * Compares the Sample with the received object.
     *
     * @param otherObject the object to be compared with the Sample
     * @return true if the received object represents other Sample
     * equivalent to the Sample. Otherwise, returns false.
     */
    @Override
    public boolean equals(Object otherObject) {
        if(this == otherObject)
            return true;

        if(otherObject == null || this.getClass() != otherObject.getClass())
            return false;

        Sample otherSample = (Sample) otherObject;

        return this.myBarcode.equals(otherSample.myBarcode);
    }


}
