@startuml
autonumber
actor "Laboratory Coordinator" as LC

participant ":CompanyPerformanceAnalysisUI" as UI
participant ":CompanyPerformanceAnalysisController" as CTRL
participant ":CompanyPerformance" as CP
'participant ":Company" as CMP
'participant ":Test" as TST
'participant "testStore\n:TestStore" as TSTSTORE
'participant "clientStore\n:ClientStore" as CLTSTORE
'participant ":Constants" as CST
'participant ":Class" as CL
'participant ":SubMaxSumAlgorithms" as SMSA
'participant ":Sum" as SUM
'participant ":BruteForceAlgorithm" as BFA

activate LC
LC -> UI : asks to see an overview of all the tests performed and \n analyse the overall performance of the company
activate UI
UI --> LC : asks the day or interval of time to analyse \n and asks the algorithm to be used
deactivate UI

loop while the Laboratory Coordinator inserts and selects different data
LC -> UI : inserts and selects the requested data (i.e., beginningDay, endingDay, chosenAlgorithm)
activate UI

UI -> CTRL : companyPerformance = setCompanyPerformance(beginningDay, endingDay, chosenAlgorithm)
activate CTRL
CTRL -> CP** : create()
CTRL --> UI : companyPerformance
deactivate CTRL

UI -> CTRL : clientInfo = getClientsInfoPerInterval()
activate CTRL
CTRL -> CP : clientInfo = getClientsNum()
activate CP
CP --> CP : clientsNum = getClientsInfoPerInterval(getDays())
CTRL --> UI : clientInfo
deactivate CP
deactivate CTRL

UI -> CTRL : numTestsProcessed = getNumTestsProcessedInterval()
activate CTRL
CTRL -> CP : numTestsProcessed = getProcessTestsNum()
activate CP
CP --> CP : processTestsNum = getNumTestsProcessedInterval(getDays())
CTRL --> UI : numTestsProcessed
deactivate CP
deactivate CTRL

UI -> CTRL : testInfoDays = getTestInfoPerDay()
activate CTRL
CTRL -> CP : testInfoDays = getTestInfoDay()
activate CP
CP --> CP : testInfoDay = getTestInfoPerDay(getDays());
CTRL --> UI : testInfoDays
deactivate CP
deactivate CTRL

UI -> CTRL : testInfoWeeks = getTestInfoPerWeek()
activate CTRL
CTRL -> CP : testInfoWeeks = getTestInfoWeek()
activate CP
CP --> CP : testInfoWeek = getTestInfoPerWeek(getDays());
CTRL --> UI : testInfoWeeks
deactivate CP
deactivate CTRL

UI -> CTRL : testInfoMonths = getTestInfoPerMonth()
activate CTRL
CTRL -> CP : testInfoMonths = getTestInfoMonth()
activate CP
CP --> CP : testInfoMonth = getTestInfoPerMonth(getDays());
CTRL --> UI : testInfoMonths
deactivate CP
deactivate CTRL

UI -> CTRL : testInfoYears = getTestInfoPerYear()
activate CTRL
CTRL -> CP : testInfoYears = getTestInfoYear()
activate CP
CP --> CP : testInfoYear = getTestInfoPerYear(getDays());
CTRL --> UI : testInfoYears
deactivate CP
deactivate CTRL

UI -> CTRL : worstSubInt = findWorstSubIntWithChosenAlgorithm()
activate CTRL
CTRL -> CP : worstSubInt = getWorstSubInt()
activate CP
CP --> CP : worstSubInt = findWorstSubIntWithChosenAlgorithm(getDays(),chosenAlg);
CTRL --> UI : worstSubInt
deactivate CP
deactivate CTRL

UI --> LC : shows an overview of the clients and tests performed, and \n shows the overall performance of the company
deactivate UI
end

@enduml