@startuml

/'Adicionei Cliente <-> Resultado'/


skinparam classAttributeIconSize 0
hide empty methods
hide empty attributes
left to right direction

class Laboratory {
- name
- address
- phoneNumber
- numTIN
}

class Employee {
- employeeID
- organizationRole
- name
- address
- phoneNumber
- e-Mail
- socCode
}

class Test{
- code
- NhsCode
- createdAt

}

class Sample{
- barCode
}

class FinalResult{}
class ChemicalResult{}
/'class ClinicalResult{}'/
class Diagnosis{}
class Parameter{
- code
- shortName
- description
}
class Notification{
- textDescription
}
/'class Courier{}'/
class SpecialistDoctorReport{}
class NHSReport{}
class Forecast{
- totalCovidNextDay
- totalCovidNextWeek
- totalCovidNextMonth
}

class NHSCovid19Data{
- numCovidTests
- positiveCovid
- totalCovidDay
- totalCovidWeek
- totalCovidMonth
- totalCovidYear
}

class Client{
- name
- citizenCardNum
- nhsNum
- birthDate
- sex
- taxIdNum
- phoneNum
- email
}
class Administrator{}

/'class Doctor{}'/
class Receptionist{}

class MedicalLabTechnician{}

class ClinicalChemistryTechnologist{}

class SpecialistDoctor{
- doctorIndexNumber
}

class LaboratoryCoordinator{}

class ClinicalAnalysisLaboratory{
- laboratoryID
}

class ChemicalLaboratory{}

class Application{}
class ChemicalAnalysis{}
/'class ClinicalAnalysis{}'/
class TestType{
- Code
- Description
- Collecting methods
}
class ParameterCategory{
- name
- code
}
/'
class Covid19Test{
}
class BloodTest{

}

class OtherTest{
}
'/

class Company{
- designation
}

/'class NHS{}'/
class NHSAPI{}
/'class ExternalModule{}'/

class LabOrder{}


/'LAYOUT PURPOSES'/
together {
class ChemicalLaboratory
class ClinicalAnalysisLaboratory
class ChemicalAnalysis
class Test
}

/'LAYOUT PURPOSES'/

Laboratory -[hidden]-> ChemicalLaboratory
Laboratory -[hidden]-> ClinicalAnalysisLaboratory


/'Company -[hidden]--> ChemicalLaboratory'/
Laboratory -[hidden]down-> Company


Test -[hidden]-> Receptionist
ClinicalAnalysisLaboratory -[hidden]-> Receptionist

/'Company -[hidden]--> ClinicalAnalysisLaboratory'/
/'ChemicalLaboratory -[hidden]down-|> ClinicalAnalysisLaboratory'/
MedicalLabTechnician -[hidden]up-|> ClinicalAnalysisLaboratory
ClinicalAnalysisLaboratory -[hidden]up-> Application
ClinicalAnalysisLaboratory -[hidden]left-|> Receptionist
/'Receptionist -[hidden]left-|> Test'/

ClinicalChemistryTechnologist -[hidden]up-|> ChemicalLaboratory
NHSReport -[hidden]down-|> Application

/' ACRESCENTEI AQUI AO RETIRAR TEST REQUESTED BY CLIENT '/
NHSReport -[hidden]up-|> Company

/'ACRESCENTEI ISTO PARA O NHSAPI FICAR EM BAIXO DO Covid19Data'/
NHSAPI -[hidden]down-|> NHSReport

/'Receptionist -[hidden]up-|> Client'/
Employee -[hidden]right-|> Company

together {
class Diagnosis
class SpecialistDoctorReport
}

/'LabOrder -[hidden]down-> Client'/
Diagnosis -[hidden]right-> SpecialistDoctorReport


/' END OF LAYOUT PURPOSES '/

Laboratory <|-- ClinicalAnalysisLaboratory
ChemicalLaboratory "1" -- "1" Laboratory : is of >
Company "1" -- "3..*" Laboratory : owns >
/'ClinicalAnalysisLaboratory "1" -- "1" Laboratory : is of >'/






Employee "*" - "1" Company : employ <
Receptionist "1" -- "1" Employee : is of >
MedicalLabTechnician "1" -- "1" Employee : is of >
ClinicalChemistryTechnologist "1" -- "1" Employee : is of >
SpecialistDoctor "1" -- "1" Employee : is of >
LaboratoryCoordinator "1" -- "1" Employee : is of >
Administrator "1" -- "1" Employee : is of >
Company "1" -- "*" Parameter : capable of analysing >
Company "1" -- "*" TestType : conducts >
Company "1" -- "*" Administrator : know >
Company "1" -- "*" ParameterCategory : adopts >
/'Company "1" -- "1" ChemicalLaboratory : owns >'/
/'Company "1" -- "1..*" ClinicalAnalysisLaboratory : owns >'/
Company "1" -- "1..*" NHSReport : reports >
Parameter "*" -- "1" ParameterCategory : presented under >
/'ACRESCENTEI LINHA ABAIXO'/
Parameter "*" -- "1" Administrator : created by >
TestType "*" -- "1" Administrator : created by >
ParameterCategory "*" -- "1" Administrator : created by >
/'RETIREI A LINHA ABAIXO TEST IS REQUESTED BY CLIENT'/
/'Test "*" -- "1" Client : requested by >'/
/'Test -- Application : is known by >'/
Test "*" -- "1" TestType : classified as >
Test "1" -- "1..*" Sample : collects >
Test "*" -- "1..*" Parameter : requested analysis of >
/'PROFFESSOR CORREÇÃO'/
/'Test "*" --- "1..*" MedicalLabTechnician : registered locally by >'/
Test "1" --- "1" LabOrder : originates <
LabOrder "1..*" --- "1" Client : provided by >
Receptionist "1" -- "*" Client : registers >
Receptionist "1" -- "*" Test : registers >
/'PERGUNTAR CLIENTE LINHA ABAIXO'/
Receptionist "1..*" - "1" ClinicalAnalysisLaboratory : works for >
/'MedicalLabTechnician "1" -- "*" Sample : collects >'/
MedicalLabTechnician "1..*" -- "1" ClinicalAnalysisLaboratory : works for >
MedicalLabTechnician "1" -- "*" Sample : records >
/'Sample -- Application : is known >'/
/'Sample "*" -- "1" ChemicalLaboratory : sent to >'/
ClinicalChemistryTechnologist "1..*" -- "1" ChemicalLaboratory : works for >
/'ClinicalChemistryTechnologist "1" -- "*" Sample : receives >'/
ClinicalChemistryTechnologist "1" - "*" ChemicalAnalysis : performs >
ClinicalChemistryTechnologist "1" -- "*" ChemicalResult : records >
/'LabOrder -- Doctor : prescribed by >'/
ChemicalResult "*" -- "1" SpecialistDoctor : analysed by >
SpecialistDoctor "1" -- "*" Diagnosis : makes >
SpecialistDoctor "1" -- "*" SpecialistDoctorReport : writes >
/'SpecialistDoctorReport -- Client : delivered to >'/
/'SpecialistDoctorReport -- Application : known by >'/
SpecialistDoctorReport "*" -- "1" LaboratoryCoordinator : validated by >
/'ClinicalResult -- Application : known by >'/
/'ClinicalResult -- LaboratoryCoordinator : validated by >'/
Diagnosis "*" --- "1" LaboratoryCoordinator : validated by >
LaboratoryCoordinator "1" -- "*" FinalResult : confirms >
Client "1" -- "1..*" Notification : receives >
FinalResult "1..*" -- "1" Client : known by >
/'Result -- MedicalLabTechnician : known by >'/
/'Result -- ClinicalChemistryTechnologist : known by >'/
/'Result -- SpecialistDoctor : known by >'/
/'Result -- LaboratoryCoordinator : known by >'/
NHSAPI "1" -- "1..*" NHSReport : receives >
Application "1" --- "1..*" NHSReport : generates >
NHSCovid19Data "1" -- "1" NHSReport : part of >
Forecast "1" -- "1" NHSReport : part of >
/'Covid19Test "*" -- "1" TestType : part of >'/
/'Covid19Test "*" -- "1" Parameter : characterized by >'/
/'BloodTest "*" -- "1" TestType : part of >'/
/'BloodTest "*" -- "3..*" Parameter : characterized by >'/
/'Application "1" - "*" TestType : supports >'/
Application "1" -- "1" Company : knows <
Application "1" - "*" Notification : sends >
/'OtherTest "*" -- "1" TestType : part of >'/
/'OtherTest "*" -- "1..*" Parameter : characterized by >'/

TestType "*" -- "1..*" Parameter : characterized by >

ClinicalAnalysisLaboratory "1..*" -- "1" Administrator : registered by >

/' US8 '/
ClinicalAnalysisLaboratory "1" -- "1..*" TestType : operates >


/'Changed specialist doctor diagnosis line 244 and 251 cause its implicit by specialist doc report'/













@enduml